
package cn.tf.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AreaInterfaceImpl", targetNamespace = "http://service.tf.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AreaInterfaceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryArea", targetNamespace = "http://service.tf.cn/", className = "cn.tf.service.QueryArea")
    @ResponseWrapper(localName = "queryAreaResponse", targetNamespace = "http://service.tf.cn/", className = "cn.tf.service.QueryAreaResponse")
    @Action(input = "http://service.tf.cn/AreaInterfaceImpl/queryAreaRequest", output = "http://service.tf.cn/AreaInterfaceImpl/queryAreaResponse")
    public String queryArea(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
